---
title: "Untitled"
author: "Guillermo Cortés, Carolina Silva, Johan Sanchez"
date: "2024-09-15"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
library(paqueteMODELOS)
library(VIM)
library(dplyr)
library(SMOTEWB)
data("rotacion")
```



```{r, echo = TRUE, warning=FALSE}
# Instalar y cargar el paquete VIM
#install.packages("VIM")


# Visualizar los valores faltantes
aggr(rotacion, col = c('navyblue', 'red'), numbers = TRUE, sortVars = TRUE, labels = names(rotacion), cex.axis = .7, gap = 3, ylab = c("Histogram of missing data", "Pattern"))
```
```{r, echo = TRUE, warning=FALSE}
summary(rotacion)
```

```{r, echo = TRUE, warning=FALSE}
rotacion$Rotación <- ifelse(rotacion$Rotación == "Si", 1, 0)
```

```{r, echo = TRUE, warning=FALSE}
head(rotacion)
```



```{r, echo = TRUE, warning=FALSE}
# Convertir Ingreso_Mensual en una variable categórica
rotacion$Satisfación_Laboral_cat <- cut(rotacion$Satisfación_Laboral, breaks = 5)

# Tabla de contingencia
tabla <- table(rotacion$Satisfación_Laboral_cat, rotacion$Rotación)

# Prueba de Chi-cuadrado
chisq.test(tabla)
```
```{r, echo = TRUE, warning=FALSE}

```


```{r, echo = TRUE, warning=FALSE}
ggplot(rotacion, aes(x = Edad)) +
  geom_histogram(binwidth = 5, fill = "blue", color = "black") +
  labs(title = "Histograma de Edad", x = "Edad", y = "Frecuencia")
```

```{r, echo = TRUE, warning=FALSE}
ggplot(rotacion, aes(y = Ingreso_Mensual)) +
  geom_boxplot(fill = "green", color = "black") +
  labs(title = "Boxplot de Ingreso Mensual", y = "Ingreso Mensual")
```

```{r, echo = TRUE, warning=FALSE}
ggplot(rotacion, aes(x = Porcentaje_aumento_salarial)) +
  geom_histogram(binwidth = 1, fill = "red", color = "black") +
  labs(title = "Histograma de Porcentaje de Aumento Salarial", x = "Porcentaje de Aumento Salarial", y = "Frecuencia")
```

```{r, echo = TRUE, warning=FALSE}
ggplot(rotacion, aes(y = Antigüedad_Cargo)) +
  geom_boxplot(fill = "purple", color = "black") +
  labs(title = "Boxplot de Antigüedad en el Cargo", y = "Antigüedad en el Cargo")
```


```{r, echo = TRUE, warning=FALSE}
rotacion$Educación <- as.factor(rotacion$Educación)
rotacion$Satisfacción_ambiental <- as.factor(rotacion$Satisfacción_Ambiental)
#rotacion$Satisfacción_laboral <- as.factor(rotacion$Satisfacción_Laboral)
rotacion$Rendimiento_laboral <- as.factor(rotacion$Rendimiento_Laboral)
rotacion$Equilibrio_trabajo_vida <- as.factor(rotacion$Equilibrio_Trabajo_Vida)
```

```{r, echo = TRUE, warning=FALSE}
table(rotacion$Rotación)
```
```{r, echo = TRUE, warning=FALSE}
class(rotacion)
```
```{r, echo = TRUE, warning=FALSE}
# Eliminar filas con valores faltantes
rotacion <- na.omit(rotacion)
rotacion <- as.data.frame(rotacion)
```



```{r, echo = TRUE, warning=FALSE}
rotacion_balanced <- SMOTEWB(Rotación ~ ., data = rotacion, perc.over = 200, perc.under = 100)
table(rotacion_balanced$Rotación)
```


```{r, echo = TRUE, warning=FALSE}
set.seed(123)  # Fijar semilla para reproducibilidad
trainIndex <- createDataPartition(rotacion$Rotación, p = 0.7, list = FALSE)
train_rotacion <- rotacion[trainIndex, ]
test_rotacion <- rotacion[-trainIndex, ]
```

```{r, echo = TRUE, warning=FALSE}
model <- train(rotacion ~ ., data = train_rotacion, method = "glm", family = binomial())
```

```{r, echo = TRUE, warning=FALSE}

```

```{r, echo = TRUE, warning=FALSE}

```

```{r, echo = TRUE, warning=FALSE}

```

```{r, echo = TRUE, warning=FALSE}

```

```{r, echo = TRUE, warning=FALSE}

```

```{r, echo = TRUE, warning=FALSE}

```


```{r, echo = TRUE, warning=FALSE}

```








